#n = str(input('Digite o seu nome completo :')).strip()
#ma = n.upper().strip()
#mi = n.lower().strip()
#print(f'O seu nome é {n}, com numeração por letras maiúsculas {ma} e com minúsculas {mi}')
#print('Seu nome tem ao todo {} letras'.format(len(n)-n.count(' ')))
#print('O seu primeiro nome tem {} letras'.format(n.find(' ')))
#separa = n.split()
#print('Seu primeiro nome é {} e ele tem  {} letras'.format(separa[0], len(separa[0])))

n = str(input('Escreva o seu nome completo:')).strip()
ni = n.upper()
na = n.lower()
print(f'Esse é o seu nome em letras maiusculas :{ni}')
print(f'Este é o seu nome em letras minúsculas :{na}')
print('Seu nome tem {} letras'.format(len(n)-n.count(' ')))
mm = n.split()
print('O seu 1º nome é {} e tem {} letras'.format(mm[0],len(mm[0])))